spring:
  jackson:
    serialization:
      indent_output: true


wikification:
  wikiXmlFile: "file:data/simplewiki-20170501-pages-meta-current.xml.bz2"
  vocabularyFile: "file:/tmp/wikificationVocabulary.txt"
  indexingConsumerCount: 5
  entityCutoffRateAfterIdentification: 0.5
  maxShingleSize: 5